import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LivePriceProvider } from "@/contexts/LivePriceContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Entry Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LivePriceProvider>
          {children}
        </LivePriceProvider>
      </body>
    </html>
  );
}
